In [67]:

import pandas as pd

data = pd.read_csv("train.csv")
data.drop(data.columns[0],axis = 1,inplace=True)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,labels
0,550,0,495,0,0,0,0,976,0,0,...,0,0,991,991,0,0,0,0,983,1
1,0,0,0,0,0,0,0,976,0,0,...,475,0,991,0,0,991,0,0,0,-1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,742,0,0,0,0,684,0,956,...,0,0,0,0,0,674,0,0,838,1
4,0,0,0,0,0,0,0,608,0,979,...,0,0,828,0,0,0,0,0,0,1

In [68]:
import seaborn as sb

#checked for outliers
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

0           0.00
1           0.00
2           0.00
3           0.00
4           0.00
5           0.00
6           0.00
7         786.00
8           0.00
9           0.00
10          0.00
11          0.00
12        713.25
13        558.00
14        301.00
15        702.00
16          0.00
17          0.00
18          0.00
19          0.00
20          0.00
21          0.00
22        501.00
23          0.00
24          0.00
25        547.25
26          0.00
27          0.00
28          0.00
29          0.00
           ...
4971        0.00
4972        0.00
4973        0.00
4974        0.00
4975        0.00
4976        0.00
4977      987.00
4978        0.00
4979        0.00
4980        0.00
4981      741.00
4982        0.00
4983        0.00
4984        0.00
4985        0.00
4986        0.00
4987      983.00
4988        0.00
4989        0.00
4990        0.00
4991        0.00
4992        0.00
4993      790.25
4994        0.00
4995        0.00
4996      659.25
4997        0.00
4998        0.00
4999        0.00
labels      2.00
Length: 5001, dtype: float64

In [69]:
#checked distribution of data
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,labels
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,...,6000.000000,6000.000000,6000.000000,6000.00000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000
mean,111.022833,11.251000,173.261167,0.951000,15.169167,50.209333,15.206333,323.073167,2.207667,146.355667,...,111.407500,2.035333,318.539667,81.03950,44.777333,263.813667,14.720667,122.423500,153.636000,0.000000
std,284.848291,91.448864,341.759463,25.771877,109.238579,194.682629,106.963813,418.413159,39.746428,317.863306,...,276.658528,41.781918,420.830651,256.10652,185.273192,394.966054,106.994417,294.247413,326.609648,1.000083
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,786.000000,0.000000,0.000000,...,0.000000,0.000000,790.250000,0.00000,0.000000,659.250000,0.000000,0.000000,0.000000,1.000000
max,999.000000,999.000000,999.000000,983.000000,999.000000,999.000000,999.000000,999.000000,991.000000,999.000000,...,999.000000,999.000000,999.000000,999.00000,999.000000,999.000000,999.000000,999.000000,999.000000,1.000000

In [70]:
#missing value check
data.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
4971      0
4972      0
4973      0
4974      0
4975      0
4976      0
4977      0
4978      0
4979      0
4980      0
4981      0
4982      0
4983      0
4984      0
4985      0
4986      0
4987      0
4988      0
4989      0
4990      0
4991      0
4992      0
4993      0
4994      0
4995      0
4996      0
4997      0
4998      0
4999      0
labels    0
Length: 5001, dtype: int64

In [71]:
# If data is balanced or not
data['labels'].value_counts()

-1    3000
 1    3000
Name: labels, dtype: int64

In [72]:
X = data.iloc[:,0:-1]
y = data.iloc[:,-1]

val_data = pd.read_csv("validation.csv")
val_data.drop(val_data.columns[0],axis = 1,inplace = True)
val_data.head()

#y.head()

,0,1,2,3,4,5,6,7,8,9,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,labels
0,688,0,0,0,0,0,0,952,0,870,...,0,0,0,0,0,494,0,769,0,1
1,778,758,0,0,0,0,0,708,0,991,...,0,0,770,0,0,0,0,0,0,1
2,469,0,816,0,0,0,0,0,0,0,...,0,0,467,0,0,0,417,0,0,-1
3,0,0,0,0,0,571,991,983,0,983,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,949,0,991,...,0,0,0,0,0,0,0,976,0,1

In [73]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.25, random_state=0)
x_validation = val_data.iloc[:,0:-1]
y_validation = val_data.iloc[:,-1]
NB = MultinomialNB()
NB.fit(X_train, y_train)
y_pred = NB.predict(X_test)
print("Naive Bayes cross validation Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = NB.predict(x_validation)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Naive Bayes cross validation Accuracy: 0.9286666666666666
Naive Bayes Accuracy: 0.922

In [74]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing 

X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = val_data.iloc[:,0:-1]
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = knn.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9786666666666667
Accuracy: 0.966

In [75]:
from sklearn import svm
from sklearn import preprocessing 

X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = val_data.iloc[:,0:-1]
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9693333333333334
Accuracy: 0.979

In [76]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import preprocessing 

X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = val_data.iloc[:,0:-1]
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
clf = AdaBoostClassifier(n_estimators=80,learning_rate=1,random_state=0)
model = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9613333333333334
Accuracy: 0.964

In [77]:
import numpy as np

corr_matrix = data.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
print(to_drop)
for val in to_drop:
    data.drop(data.columns[int(val)], axis=1)
for val in to_drop:
    val_data.drop(data.columns[int(val)], axis=1)
print("done")

x_train_drop = data.iloc[:,0:-1]
y = data.iloc[:,-1]

x_validation_drop = val_data.iloc[:,0:-1]
y = data.iloc[:,-1]

['989', '998', '1004', '1105', '1228', '1245', '1412', '1434', '1462', '1543', '1550', '1600', '1601', '1676', '1704', '1747', '1774', '1825', '1901', '1946', '2027', '2066', '2070', '2160', '2163', '2166', '2276', '2339', '2343', '2355', '2371', '2389', '2423', '2427', '2462', '2511', '2531', '2550', '2576', '2602', '2674', '2675', '2703', '2706', '2785', '2814', '2841', '2847', '2851', '2898', '2930', '2939', '2955', '2960', '2997', '3019', '3084', '3106', '3109', '3146', '3149', '3170', '3174', '3194', '3212', '3261', '3326', '3396', '3437', '3512', '3583', '3654', '3659', '3712', '3803', '3824', '3851', '3882', '3885', '3910', '3925', '3937', '3941', '3951', '3959', '4017', '4051', '4055', '4087', '4099', '4116', '4127', '4148', '4159', '4236', '4256', '4386', '4396', '4412', '4451', '4474', '4499', '4509', '4631', '4650', '4652', '4670', '4750', '4796', '4804', '4856', '4875', '4891', '4934', '4947', '4966', '4992']
done

In [105]:

import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

X_train, X_test, y_train, y_test = train_test_split(x_train_drop , y, test_size=0.25, random_state=0)
x_validation = x_validation_drop
y_validation = val_data.iloc[:,-1]
gnb = MultinomialNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = gnb.predict(x_validation)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Naive Bayes Accuracy: 0.9286666666666666
Naive Bayes Accuracy: 0.922

In [106]:
X_train, X_test, y_train, y_test = train_test_split(x_train_drop , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = x_validation_drop
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = knn.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9786666666666667
Accuracy: 0.966

In [107]:
X_train, X_test, y_train, y_test = train_test_split(x_train_drop , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = x_validation_drop
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
svm = svm.SVC(kernel = 'linear')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = svm.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9693333333333334
Accuracy: 0.979

In [108]:
X_train, X_test, y_train, y_test = train_test_split(x_train_drop , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = x_validation_drop
x_validation = preprocessing.normalize(x_validation)
y_validation = val_data.iloc[:,-1]
ad_boost = AdaBoostClassifier(n_estimators=80,learning_rate=1,random_state=0)
model = ad_boost.fit(X_train, y_train)
y_pred = ad_boost.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = ad_boost.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9613333333333334
Accuracy: 0.964

In [5]:
from sklearn.linear_model import LogisticRegression

x_train =  X
y_train = y
x_validation = val_data.iloc[:,0:-1]
y_validation = val_data.iloc[:,-1]
logistic = LogisticRegression()
logistic.fit(x_train, y_train)
predictions = logistic.predict(x_validation)
score = logistic.score(x_validation, y_validation)
print(score)

C:\Users\Virendra\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.982

In [84]:
#feature Engineering
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

x_train =  X
y_train = y
x_validation = val_data.iloc[:,0:-1]
y_validation = val_data.iloc[:,-1]
random_forest_FS = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)
random_forest_FS.fit(x_train,y_train)
selector = SelectFromModel(random_forest_FS, threshold=0.00001)
selector.fit(x_train, y_train)
x_train_new = selector.transform(x_train)
x_validation_new = selector.transform(x_validation)
print(x_train_new.shape)

(6000, 3987)

In [85]:
print(x_validation_new.shape)

(1000, 3987)

In [88]:
X_train, X_test, y_train, y_test = train_test_split(x_train_new , y, test_size=0.25, random_state=0)
x_validation_new = x_validation_new
y_validation = val_data.iloc[:,-1]
gnb = MultinomialNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = gnb.predict(x_validation_new)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Naive Bayes Accuracy: 0.9293333333333333
Naive Bayes Accuracy: 0.925

In [89]:
X_train, X_test, y_train, y_test = train_test_split(x_train_new , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_new)
y_validation = val_data.iloc[:,-1]
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = knn.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9786666666666667
Accuracy: 0.968

In [92]:
from sklearn import svm
from sklearn import preprocessing 

X_train, X_test, y_train, y_test = train_test_split(x_train_new , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_new)
y_validation = val_data.iloc[:,-1]
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9686666666666667
Accuracy: 0.979

In [93]:
X_train, X_test, y_train, y_test = train_test_split(x_train_new , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_new)
y_validation = val_data.iloc[:,-1]
clf = AdaBoostClassifier(n_estimators=80,learning_rate=1,random_state=0)
model = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.9626666666666667
Accuracy: 0.97

In [94]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

x_train =  X
y_train = y
x_validation = val_data.iloc[:,0:-1]
y_validation = val_data.iloc[:,-1]
xgb_FS = model = XGBClassifier()
xgb_FS.fit(x_train,y_train)
selector = SelectFromModel(xgb_FS, threshold=0.000001)
selector.fit(x_train, y_train)
x_train_xgb = selector.transform(x_train)
x_validation_xgb = selector.transform(x_validation)
print(x_train_xgb.shape)

(6000, 298)

In [95]:
X_train, X_test, y_train, y_test = train_test_split(x_train_xgb , y, test_size=0.25, random_state=0)
y_validation = val_data.iloc[:,-1]
gnb = MultinomialNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(x_validation_xgb)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_validation, y_pred))
y_pred = gnb.predict(x_validation_xgb)
print("Naive Bayes Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Naive Bayes Accuracy: 0.943
Naive Bayes Accuracy: 0.943

In [97]:
X_train, X_test, y_train, y_test = train_test_split(x_train_xgb , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_xgb)
y_validation = val_data.iloc[:,-1]
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = knn.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.984
Accuracy: 0.982

In [114]:
X_train, X_test, y_train, y_test = train_test_split(x_train_xgb , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_xgb)
y_validation = val_data.iloc[:,-1]
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.98
Accuracy: 0.977

In [104]:
X_train, X_test, y_train, y_test = train_test_split(x_train_xgb , y, test_size=0.25, random_state=0)
X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
x_validation = preprocessing.normalize(x_validation_xgb)
y_validation = val_data.iloc[:,-1]
clf = svm.SVC(kernel = 'linear')
clf = AdaBoostClassifier(n_estimators=80,learning_rate=1,random_state=0)
model = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_pred = clf.predict(x_validation)
print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

Accuracy: 0.964
Accuracy: 0.961

In [ ]:
#References
#https://chrisalbon.com/machine_learning/feature_selection/drop_highly_correlated_features/
#https://www.datacamp.com/community/tutorials/naive-bayes-scikit-learn
#https://www.datacamp.com/community/tutorials/k-nearest-neighbor-classification-scikit-learn
#https://www.datacamp.com/community/tutorials/svm-classification-scikit-learn-python
#https://www.datacamp.com/community/tutorials/ensemble-learning-python
#https://chrisalbon.com/machine_learning/trees_and_forests/feature_selection_using_random_forest/